name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build-example:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v33
        with:
          nix_conf: |
            extra-experimental-features = impure-derivations ca-derivations

      - run: nix --accept-flake-config profile install github:juspay/vira

      - name: CI
        run: vira ci --only-build

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
